### ISSUE TITLE
Screen freezes (only video) for a couple of seconds Windows 11 Legion Go

### ISSUE THREAD

**Issue by ibrahimqatar** [streetpea/chiaki-ng#219]
the is an issue that the stream hangs for a couple of seconds while audio is going through just fine.

it happens randomly, I had it captured in the log file (only happened once then I closed the session after it resumed from being hanged.

[chiaki_session_2024-01-22_00-09-06-083083.log](https://github.com/streetpea/chiaki4deck/files/14002852/chiaki_session_2024-01-22_00-09-06-083083.log)

my ps5 is using Lan and my internet speed is 1gbps. the settings used is 50000mbps (it will have the same issue even if it's 15000)

this is a speed test on my legion go using wifi:

<img width="567" alt="Screenshot 2024-01-22 002046" src="https://github.com/streetpea/chiaki4deck/assets/18020735/6379610d-32b0-46a1-9c4f-26a68e7e5e1d">

Update:

I am using port forwarding on my router to be able to connect outside my house, if this causes the problem, what is the alternative?

**Comment by rhysnewell** [comment]
I have had similar issues, the solution for me was to unplug the HDMI connecting the playstation to the TV that it was hooked up to. These video freezes only occurred when the TV was turned off and in rest mode. Streaming while TV was on did not have any lag spikes. I think this might be an issue with playstation's remote play rather than Chiaki4Deck
