### ISSUE TITLE
Request to edit, organize, and hide consoles in the menu

### ISSUE THREAD

**Issue by Mindofone** [streetpea/chiaki-ng#267]
My dad and I both have PS5s and I keep seeing his console in the list. There is never going to be a scenario I would want to connect to his console, so could there be a way to hide other consoles on your network? Maybe not permanently, but at least create a collapsible menu for "hidden" consoles. Being able to arrange consoles, and even designate a favorite that always appears at the top of the list would be just as good. I love using Chiaki, thanks for working on the project guys!

**Comment by Luminlyre** [comment]
Good evening! Not sure if this will be of any help but check out the automation options (Link below). By using that you will only ever connect to your ps5 IP and be able to bypass the config screen completely. If you ever want to make changes or edits just start the chiaki4deck app manually instead of using the .sh launcher. Hope this helps, cheers!

https://streetpea.github.io/chiaki4deck/setup/automation/#
