### ISSUE TITLE
[BUG] DualSense Controller Lack of Haptic Feedback on MacOS

### ISSUE THREAD

**Issue by KrisCris** [streetpea/chiaki-ng#379]
**Describe the bug**
The rumble is very weak and no haptic feedback at all.

**Debug Log**
[chiaki_session_2024-08-01_00-01-10-968968.log](https://github.com/user-attachments/files/16444413/chiaki_session_2024-08-01_00-01-10-968968.log)

**To Reproduce**
Open a game like ASTRO's PLAYROOM, test the controller.

**Expected behavior**
The rumble should resemble what it is like on PS5

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 15.1
 - Device: MacBook Air M2
 - chiaki-ng Version: 1.8.0

**Comment by streetpea** [comment]
Right now only emulated rumble is available on MacOS as the haptic feedback doesn't work played via SDL through the dualsense audio device on MacOS ... the official app does have rumble on MacOS so maybe it's possible but i'm not sure how ... maybe @jbaiter has some insights into this?

**Comment by jbaiter** [comment]
I unfortunately neither own a Mac nor have any idea about the audio APIs available on MacOS. This will require either reverse engineering how the official app does it or someone well versed in MacOS Audio APIs, ideally both,  I'm afraid :-/

**Comment by streetpea** [comment]
Given core audio is the only driver on MacOS in SDL and it doesn’t work now, we would likely need to use something other than SDL to get it working.

**Comment by streetpea** [comment]
so I re-enabled it for a future release. The problem of why it wasn't working in general before (when it was enabled) is because by default MacOS has it as a stereo speaker. You need to go to the Audio MIDI Setup utility and configure it as `Quadrophonic` and it works. I added instructions on how to do this (it appears this only needs to be done once and persists after restarts from my testing) to the docs on the Controlling section of the Setup (the new docs will be published with the new release where it is enabled at a later date but you can see a markdown version of them here: https://github.com/streetpea/chiaki-ng/blob/main/docs/setup/controlling.md#enabling-dualsense-haptics-on-macos [note it won't be pretty rendered like the actual web page will be])
