### ISSUE TITLE
[BUG]ChiakiNG Freezes after 20m and Disconnects

### ISSUE THREAD

**Issue by ArchTheOni** [streetpea/chiaki-ng#386]
**Describe the bug**
it works great but after 20 minutes the screen on the steamdeck freezes and 2 seconds later it disconnects from remote play meaning i have to completely restart chiaki ruining whatever experience i was having on my ps5

**Debug Log**
i dont know how to get a debug log if someone can let me know i will post one

**To Reproduce**
literally just play for 20 minutes and it just freezes

**Expected behavior**
i dont expect it to freeze 

**Desktop (please complete the following information):**
 - OS: [SteamOS]
 - Version [Stable]
 - Device [Steam Deck]
 - chiaki-ng Version [1.8.0]

**Additional context**
honestly i just kinda want it to be fixed

**Comment by Traillaitor** [comment]
I had this issue. I did some tinkering and found out that the issue is with IPv6. It causes dropped packages and dropped connections - not just with steam deck but remote play in general (I tried with PS Portal).

I disabled IPv6 in my router settings and haven’t had a single issue since. Previously disconnections were every 15 minutes. I played last night for 3 hours with no problems at all.

**Comment by ArchTheOni** [comment]
> I had this issue. I did some tinkering and found out that the issue is with IPv6. It causes dropped packages and dropped connections - not just with steam deck but remote play in general (I tried with PS Portal).
> 
> I disabled IPv6 in my router settings and haven’t had a single issue since. Previously disconnections were every 15 minutes. I played last night for 3 hours with no problems at all.

i just disabled ipv6 im gunna try it out!!

**Comment by boboshu** [comment]
me too ! Freezes after 1hous

**Comment by streetpea** [comment]
Dup of #130
