### ISSUE TITLE
PS5 Pro Support

### ISSUE THREAD

**Issue by streetpea** [streetpea/chiaki-ng#404]
**Is your feature request related to a problem? Please describe.**

chiaki-ng probably won’t work on ps5 pro out of the box (such us having some new options that aren’t currently in chiaki-ng)

**Describe the solution you'd like**

to be able to remote play ps5 pro using chiaki-ng

**Describe alternatives you've considered**

There won’t really be an alternative if the user sells their ps5 for a ps5 pro or doesn’t have a ps5 to begin with.

**Additional context**

none needed

**Comment by streetpea** [comment]
I’ll get a ps5 pro to test this out and do the necessary upgrades. If anyone else is getting a ps5 pro and wants to help lmk.

**Comment by zutmkr** [comment]
Im very curoius if thay will bump stream resolution to like 1440p at least. I'm thinking to preorder one, so if that happens I will gladly help to get the chiaki working for PS5 pro.

**Comment by streamingdv** [comment]
@zutmkr to be honest I don't think so, maybe 1440p but I don't think 4k is going to happen as this would significantly increase the need for the video decoding capability of the PS5 device. But we will see 💪

**Comment by Entropy512** [comment]
I do wonder if PS5 Pro will actually break anything if you use it in "backwards compatible" modes.  After all I don't think there was anything special needed for PS4 vs PS4Pro other than possibly some new resolution modes.

Obviously the Pro-specific resolutions (if there are any that aren't already supported by PS5, just at higher texture resolutionns and framerates) would be a nice to have.

I haven't contributed anything yet, but as someone who is working on a downstream project ( https://github.com/Entropy512/libchiaki_cython - cython bindings for libchiaki) and is probably going to get a PS5Pro (although possibly not at launch depending on whether the games I play are adding Pro support this time around), I'll definitely be taking a look at this.  Of course since my current focus is commandline controller input, additional resolutions/framerates aren't on my list since I'm literally throwing the video data out after setting it to the lowest resolution/framerate I can...

**Comment by fabrecordz** [comment]
I preordered Ps5 Pro and I would like to assist with this in any way I can.

**Comment by zutmkr** [comment]
Getting ps5 tommorow. @streetpea pm me on discord @kruhol so we can schedule a quick call of how I can help you to get the app compatible and working.

**Comment by Rahzadan** [comment]
@streetpea I can confirm that PS5 Pro just works. 

I'm obviously not sure if it's capable of higher than 1080p / 60fps through Chiaki, but I can confirm everything works just the same as it did on my PS5!

**Comment by streetpea** [comment]
@Rahzadan Does remote connection via psn work as well?

**Comment by Rahzadan** [comment]
@streetpea I can't seem to get remote connection to work, but maybe I'm doing it wrong... I never actually used remote connection before now (I clicked the wifi symbol in the corner of Chiaki so there was a line though it). When I tried connecting, I did notice that uPnP on my router did have ports 9308, 8572, 9303 and 9297 open on the PS5 Pro. I tried it while my PS5 Pro was in standby and it woke up when trying a remote connection, bvut never connected.

Here's the log:

`[2024-11-07 23:28:03:199199] [I] Chiaki Version 1.9.1
[2024-11-07 23:28:03:200200] [I] Trying to use hardware decoder "vulkan"
[2024-11-07 23:28:03:200200] [I] Using hardware decoder "vulkan" with pix_fmt=vulkan
[2024-11-07 23:28:05:159159] [I] >> Created session
[2024-11-07 23:28:05:160160] [I] ChiakiOpusEncoder initialized
[2024-11-07 23:28:05:160160] [I] Controller 0 opened: "DualSense Wireless Controller (030057564c050000e60c000000006800)"
[2024-11-07 23:28:05:169169] [I] Duid: 00000007000a00c0000102900020000076c1cccef8aa60be92e38d59a10131de
[2024-11-07 23:28:06:160160] [W] DualSense features were enabled and a DualSense is connected, but could not find the DualSense audio device!
[2024-11-07 23:28:13:176176] [I] Failed to find UPnP-capable devices on network: err=0
[2024-11-07 23:28:13:900900] [I] Calculating packet allocation based on 4 responses with the same address
[2024-11-07 23:28:13:900900] [W] Got different allocation increment calculations from different ports.
Increment 0: 36392, Increment 1: 43192, Increment 2: 30150
[2024-11-07 23:28:13:900900] [I] holepunch_session_create_offer: IPV6 NOT supported by your PlayStation console. Skipping IPV6 connection
[2024-11-07 23:28:13:900900] [I] >> Created offer msg for ctrl connection
[2024-11-07 23:28:14:898898] [E] websocket_thread_func: Sending WebSocket PING failed with CURL error Failed sending data to the peer.
[2024-11-07 23:29:14:759759] [E] wait_for_notification: Timed out waiting for holepunch session messages
[2024-11-07 23:29:14:759759] [E] chiaki_holepunch_session_start: Timed out waiting for holepunch session start notifications.
[2024-11-07 23:29:14:759759] [E] !! Failed to start session`

I noticed a message about failing to find a UPnP-capable device.... but I'm on the same network, and the PS5 Pro was successful in opening several ports. I should note that I'm on the windows x64 version (Win11), Chiaki-ng 1.9.1

**Comment by Rahzadan** [comment]
I should also note that chiaki seems to randomly crash to desktop (no error) after it fails to connect with nothing additional in the log.

**Comment by Rahzadan** [comment]
@streetpea Remote PSN connection is also working fine on PS5 Pro!

The issue was on my end. For some reason my Decktop PC was having issues establishing a uPnP connection to my router. I tried on my laptop and it worked perfectly. I went to a public WiFi hotspot and it worked from there too:

>   [2024-11-09 10:35:11:817817] [I] Added local UPNP port mapping to port 50511
[2024-11-09 10:35:13:214214] [I] Sent response to 47.54.105.94:9303
[2024-11-09 10:35:13:725725] [I] Sent response to 47.54.105.94:9303
[2024-11-09 10:35:14:237237] [I] Sent response to 47.54.105.94:9303
[2024-11-09 10:35:16:914914] [I] >> Punched hole for control connection!

**Comment by Rahzadan** [comment]
@streetpea Remote PSN connection is also working fine on PS5 Pro!

The issue was on my end. For some reason my Decktop PC was having issues establishing a uPnP connection to my router. I tried on my laptop and it worked perfectly. I went to a public WiFi hotspot and it worked from there too:

[2024-11-09 10:35:11:817817] [I] Added local UPNP port mapping to port 50511
[2024-11-09 10:35:13:214214] [I] Sent response to (public ip):9303
[2024-11-09 10:35:13:725725] [I] Sent response to (public ip):9303
[2024-11-09 10:35:14:237237] [I] Sent response to (public ip):9303
[2024-11-09 10:35:16:914914] [I] >> Punched hole for control connection!

**Comment by L0WR1D3Rz** [comment]
Streetpea i opened an issue. I have the ps5 pro. All works well in same wifi but it won't see the console when I try to connect via PSN. How can I help to fix this? I'm in 1.9.1 and use steamdeck oled for remote play

**Comment by streetpea** [comment]
@Rahzadan it doesn’t require upnp, but if you enable upnp it should always work independent of the network type. In this case it’s not actually the remote play he’s saying is failing though but the listing of the console via calling the psn api.

It seems that works for you though at rhazadan, since you can see the remote play via psn tab to select it.

**Comment by Rahzadan** [comment]
@streetpea I couldn't get remote PSN connection to work at all without uPnP, otherwise I have to manually forward the ports in my router (which did work before you implemented pan connection). I also get the upnp error I posted a few posts above if upnp isn't working. Doesn't the PSN api invoke the console (and the Chiaki client) to hole-punch the ports it needs for a remote connection? How could it work otherwise?

**Comment by streetpea** [comment]
There is two separate sections. The first is to discover consoles registered with psn. This is the how the console is listed. Next, is the actual udp hole punching. This enables a direct connection to the console from the client, using psn to exchange information between parties. This works in the majority (~92% based on statistics from googles remote connection turn service) of networks. However, in the other 8% of networks you won’t be able to make a connection. Enabling upnp means you open a hole yourself so the hole doesn’t actually need to be punched so it will always work even if you are using an incompatible network.

**Comment by Rahzadan** [comment]
@streetpea Thank you for clarifying! Is it possible that the 8% you speak of are those that are on a network where either there is no uPnP, or uPnP isn't working correctly? In my case, my network DOES have working uPnP, but on 1 particular PC in my house, for some reason it doesn't work (probably my PC's fault). My laptop, which IS on the exact same network, DOES work when I enable remote PSN (clicking the symbol in the lower left corner of Chiaki). On both my PC and Laptop, the PS5 creates the uPnP entries in my router and "hole punches" through the firewall. On my laptop, it also creates a couple of uPnP entries, however my PC does not (getting the "failed to find uPnP-capable devices" error).

Here are the verbose logs for both my non-working PC, and my working lapaop. Note that I redacted some info that looked personally identifiable... If you also need that info please let me know.

[Verbose log - PC (Desktop) not working.log](https://github.com/user-attachments/files/17690105/Verbose.log.-.PC.Desktop.not.working.log)
[Verbose log - Laptop working.log](https://github.com/user-attachments/files/17690110/Verbose.log.-.Laptop.working.log)

Here are the uPnP entries created by my Laptop:

<img width="756" alt="image" src="https://github.com/user-attachments/assets/76f887c7-2ed0-4bdf-afd7-f3538f3d3eaf">

**Please also let me know if there's anything I can do on my end to determine if the PS5 Pro is capable of streaming in anything higher or different than 1080p 60fps**

**Comment by Rahzadan** [comment]
@streetpea Sorry, re-uploading my Laptop's verbose log as I realized the one above wasn't verbose..oops!

[Verbose Log - Laptop working.log](https://github.com/user-attachments/files/17690143/Verbose.Log.-.Laptop.working.log)

**Comment by streetpea** [comment]
Upnp punches it own holes so you don’t really need to do the holepunching . That is a surefire wire to get things working so is tried first and then if that doesn’t work it uses STUN and actually does the udp hole punching.

**Comment by L0WR1D3Rz** [comment]
> @L0WR1D3Rz, PSN connection relies on uPnP. Make sure it's enabled in your router.

Since it works fine using official Android app though, shouldn't it work on steam deck as well? Or is Upnp necessary only for chiaki?

**Comment by Rahzadan** [comment]
@streetpea In my case above with my Desktop PC, it seems even STUN didn't work, however. Doesn't STUN still rely on uPnP though? My understanding is that STUN is used by uPnP when it can't otherwise determine the external IP address.

**Comment by streetpea** [comment]
@Rahzadan the verbose log you posted for the not working one just shows psn failing to find the ps5. This means the ps5 is temporarily unavailable via psn. Either the console isn’t connected to psn currently such as being completely off or more likely a connection has just completed so the ps5 is showing unavailable for a short period of time (a cooldown). Please try again and post the updated log.

**Comment by streetpea** [comment]
@Rahzadan no

**Comment by Rahzadan** [comment]
> @Rahzadan the verbose log you posted for the not working one just shows psn failing to find the ps5. This means the ps5 is temporarily unavailable via psn. Either the console isn’t connected to psn currently such as being completely off or more likely a connection has just completed so the ps5 is showing unavailable for a short period of time (a cooldown). Please try again and post the updated log.

@streetpea The log for my non-working connection from my Desktop PC is the same every time, and it also fails every time, regardless of cooldown (been spending way too much time on this, lol) I should also mention that GAMES that I try to play (like Call of Duty) which use uPnP opn my desktop PC also fail to open a uPnP port. For some reason my Desktop cannot establish communication with uPnP running on my router, but my laptop can.

If my desktop couldn't find the PS5 at all (via PSN), how is it that the PS5 still wakes from standby, but doesn't establish the video stream? The common denominator I see is the uPnP error in my desktop's logs.

I will try and see why uPnP is failing on my Desktop, and will let you know if it starts working when I fix that.

**Comment by streetpea** [comment]
@Rahzadan I see you updated the log. You’re actually running into a problem I’ve fixed in main. Which platform are you using so I can give you a build to try?

**Comment by streetpea** [comment]
@Rahzadan I see you updated the log. You’re actually running into a problem uI’ve fixed in main. Try this windows build: https://github.com/streetpea/chiaki-ng/actions/runs/11751482964/artifacts/2165714691. Should fix your issue

**Comment by Rahzadan** [comment]
@streetpea So as a test, I just disabled uPnP in my router:

<img width="400" alt="{4EDB138E-FA41-420C-B949-25F4A0D87BD2}" src="https://github.com/user-attachments/assets/6564269d-df5c-42b9-8ca8-f9feb8314bdd">

After doing this, my Laptop now **also fails to connect** via PSN. 

Here is the verbose log for my (previously working) laptop, now failing due to uPnP being disabled:

[Verbose log - Laptop with uPnP disabled on router.log](https://github.com/user-attachments/files/17690251/Verbose.log.-.Laptop.with.uPnP.disabled.on.router.log)

@streetpea I saw your above post while I was typing this one....lol. I will try your test build and let you know!

**Comment by Rahzadan** [comment]
@streetpea With the above test build, PSN remote now works on my desktop and laptop regardless if uPnP is enabled or not.

I did notice that it's slightly hit-or-miss though, but that may have to do with the PSN network or other factors. What I mean by that, is that if my PS5 Pro is in standby/sleep mode first, chiaki will sometimes fail to connect **via PSN** (it always connects every time using local connection, regarless of PS5 sleep state). If my PS5 is already awake, chiaki now seems to always connect via PSN whether or not uPnP is enabled in my router.

I do still get the **"Failed to find UPnP-capable devices"** error in the logs, but it still connects now despite that error. Whatever you changed in the test build helped tremendously.

Now to figure out why my desktop PC can't see uPnP on my router... but that's a separate "me" problem now... haha.

**Comment by streetpea** [comment]
@Rahzadan which error are you getting in those cases? It sounds like what you’re describing is trying to contact the PlayStation when it isn’t connected to psn. PSN is used to wake up the console from sleep mode.  The console disconnects from psn initially when going to sleep or when finishing another connection. In this case, upon failing the chiaki-ng screen should prompt you to try again.

**Comment by streetpea** [comment]
@Rahzadan failing to find upnp devices isn’t an error for chiaki-ng. Errors are denoted in the logs with [E] … that is an info log denoted with [I]

**Comment by Rahzadan** [comment]
@streetpea I just now tried it again after letting the PS5 sit in sleep mode for about 10 minutes, and it worked fine. May have been because I wasn't letting it cool down long enough like you mentioned in an above post. Got a little too hasty I think!

**Comment by Rahzadan** [comment]
@streetpea Not sure if this helps, but all the posts above when I was talking about my Laptop working with uPnP and my desktop not working, was because my Laptop was running Chiaki-ng 1.9.0 and my desktop was running 1.9.1. After putting 1.9.1 on my Laptop, uPnP stopped working. Conversly, when I rolled back to 1.9.0 on my Desktop, uPnP started working again. I opened issue #474 to address this.

**Comment by streetpea** [comment]
Nothing new needed for ps5 pro
