### ISSUE TITLE
No Video Option?

### ISSUE THREAD

**Issue by theblackdawn** [streetpea/chiaki-ng#405]
Is there an option to turn off video streaming for Chiaki? A pointer to what would need to be edited would be enough to get me going.

**Comment by streetpea** [comment]
There is no ability to just stream audio from remote play. Having said that, you can get a headless stream using the stream command. You can see how to set up a script using this command in the automation section: https://streetpea.github.io/chiaki-ng/setup/automation/. You can then pipe this stream output somewhere else like to mpv. See the pr for the stream command before it got merged into chiaki (after it moved to source hut which is the GitHub has it as not merged in case you’re wondering). https://github.com/thestr4ng3r/chiaki/pull/278 Hopefully that helps. Since just streaming audio is not possible via the remote play serving running on the console (managed in firmware on the console by Sony). I’m closing this issue.
