### ISSUE TITLE
Chiake disable vídeo 

### ISSUE THREAD

**Issue by Mdpt1995** [streetpea/chiaki-ng#425]
Good evening, I would like to know if it is possible in the source code to disable the video and audio and leave it as a gamepad.

**Comment by streetpea** [comment]
No it’s not

**Comment by Mdpt1995** [comment]
strange, there is a guy who modified the chiaki so that it can only run a gamepad without video and audio input

**Comment by streetpea** [comment]
You can of course discard video and audio if you want.

**Comment by streetpea** [comment]
@Mdpt1995 maybe @entropy512 could help you? He mentioned working on a downstream project that discards video data … https://github.com/Entropy512/libchiaki_cython

**Comment by Entropy512** [comment]
So FYI, in my downstream project, I haven't yet completely eliminated the console sending video data.  I'm not sure if there are any projects that do this.  I set the console to set video data to the lowest possible bandwidth, and then discard what arrives, so at least there's no decoding overhead.  I haven't yet looked into whether it's possible to reduce bandwidth even further than the "predefined" profiles within libchiaki or stop video transmission by the console entirely.  (I would not be surprised if the latter is impossible.)

It's a "nice to have" for my use case, but so far, I have to admit, since it's "mostly working for my purposes", I haven't been hugely motivated to go that final stretch.  I can tell you that sending input events immediately the moment they come from a controller can have Bad Results, so I now have a rate-limiter that will not send an input event until the last event was sent 4ms ago (250 Hz).  I'd like to tap into libchiaki's flow/congestion control so that this drops even further if things back up, but that's also TODO.  (Not sure if this is implemented in the upper levels of the chiaki app.  The boundaries between libchiaki and the app are...  a little bit grey.  :) )

Warning:  Reading my code in its current state will probably scar you for life, since one of my primary goals was learning Cython.  :)  Cleaning it up IS on my TODO list, but since it now meets my own personal needs I've been bad about cleaning it up!  :)

I think there do appear to be some things missing in the flow/congestion control aspects of libchiaki (admittedly, I do need to update the library and retest), for example, I do on occasion see this error trigger coming from takion.c line 1202 (probably has changed, need to pull/rebuild/update) which hints at "we don't fully understand the protocol's congestion control/retransmission/flow control":

```
        if(buf_size != 0xc)
        {
                CHIAKI_LOGE(takion->log, "Takion received data ack with size %#x != %#x", buf_size, 0xc);
                return;
        }

```

The remoteplay service on the console crashing seems to happen after one of the streams' flow control/retransmission algorithm backs up.  This happens less often now that I've coalesced input events from the controller, but hasn't been entirely eliminated.

**Comment by streetpea** [comment]
@Mdpt1995 there is now an option to disable audio and/or video. It doesn’t stop the console from sending it but makes it as small as possible and discards before processing. See https://github.com/streetpea/chiaki-ng/actions/runs/12967705481/artifacts/2485559196 for the test build.
