### ISSUE TITLE
Different assignments for touching different parts of Touchpad

### ISSUE THREAD

**Issue by Jayinem** [streetpea/chiaki-ng#442]
Only on certain games such as Alan Wake 2 on PS5 for example, does this apply but if you hit the left side of the touchpad it does something than if you hit the right side. I would love to have this added to Chiaki-NG where you can assign different keys or different buttons to different parts of the touchpad. Other than that this is pretty much perfect.

**Comment by streetpea** [comment]
Touch support is implemented for controllers with touch pads, touch screens. And mice via click and drag.

**Comment by streetpea** [comment]
It is all dependent on where you touch the touch pad (or click on the screen with a mouse)

**Comment by Jayinem** [comment]
Yeah but I'm using a Wii U Pro with no touchpad, due to having about 8 to 10x as long battery life than Playstation controllers. I hate charging controllers after one 3-5 hour game session.

**Comment by streetpea** [comment]
I like your suggestion. I think I could add touchpad button + dpad to do a touch either in the far middle left, in the far right, in the top or in the bottom. You could then also combine these for directional swipes potentially. How does that sound?

**Comment by Jayinem** [comment]
Awesome, exactly what I was hoping for. Thank you

**Comment by streetpea** [comment]
@Jayinem here is a windows build with dpad touch emulation. Dpad left is the far left side of the screen and middle height the screen, dpad right is the far right side of the screen and middle height of the screen, dpad up is top of the screen middle width of the screen and dpad down is bottom of the screen middle width of the screen. If you press another dpad button after the initial press within 0.5 second it will register is a new touch at touchpad increment (defaults to 0.3 mm but can update in settings under settings->Controllers) so if you want to do a touchpad swipe from left to right you would press dpad left followed by holding dpad right for a bit

**Comment by e-t-l** [comment]
I am using the latest version (v1.9.1) of chiaki-ng on Windows with an Xbox One controller, trying to use touchpad swipes in Ghost of Tsushima, and they're not working. I have enabled the settings as described in https://streetpea.github.io/chiaki-ng/setup/controlling/#dpad-touch-emulation and set the Share button (b6) to be the "Touchpad button" as suggested. 

If I press the share button on my XB1 controller, it is interpreted as a basic touchpad click. However, combining it with "swipes" on the D-pad are STILL interpreted as a basic touchpad click and a normal D-pad press, NOT as a touchpad swipe. (Ghost of Tsushima has controls bound to the D-pad by default, and these are what get triggered when I try to do the touchpad button + dpad swipe combo).

The issue appears to be that the share button press is getting interpreted immediately as a touchpad click, so any other button presses, like a D-pad press, get interpreted as a totally separate button press. I'm not sure if I'm doing something wrong (and would appreciate any advice on how to do it properly!) but if this is indeed a bug, I have a suggested fix:

Instead of firing the touchpad click input immediately on the assigned button's downpress, fire it when the button is RELEASED. That way, If the touchpad button is pressed and released immediately, it will be interpreted as a touchpad click. However, if the touchpad button is HELD DOWN while other buttons (d-pad) are pressed, it will be interpreted as a TOUCHPAD SWIPE COMBO.

**Comment by streetpea** [comment]
@e-t-l for a touchpad swipe you wouldn't use the touchpad click button

**Comment by e-t-l** [comment]
> for a touchpad swipe you wouldn't use the touchpad click button

Ok, re-readingthe documentation I see that that since touchpad button + d-pad button = touchpad side click, I had assumed the following instructions about pressing one d-pad direction and then another would also require the touchpad button to be pressed.

Regardless, following the instructions literally ("For a swipe from left to right: First touch dpad left and then hold dpad right for a second or so") does not work for me. The game registers the input as a d-pad left press followed by a d-pad right press. (Ghost of Tsushima already has controls mapped to the d-pad, and these are the controls that get fired)

I am using an Xbox One controller connected by USB to a Windows 11 PC running Chiaki to remotely play my PS4.

**Comment by e-t-l** [comment]
Ok, after tweaking the touch increment setting, I can get *some* swipes to work. Specifically, I can trigger the rightward-swipe by pressing d-pad up then holding d-pad right. I can do an upward swipe by pressing d-pad right then holding d-pad up. Other combinations do not work (for example, press d-pad left then hold d-pad right) because the game's standard d-pad button assignments get triggered instead. I suspect this is because the game has controls assigned to the d-pad's left and down buttons, but not the right or up (which is why I can use combinations of d-pad right and up to trigger touchpad swipes).

So, it's looking like using the d-pad for touchpad emulation ONLY really works if the game does not already have d-pad controls assigned. 

I stand by my original conclusion: The most effective solution would be for the assigned touchpad button (the share button, in my case, or whatever else the user chooses) to act like a MODIFIER KEY: When it is held down, the d-pad ONLY functions for touchpad swipes; when it is not pressed, the d-pad ONLY sends normal d-pad inputs. 

@streetpea I'm curious to hear what you think!

**Comment by streetpea** [comment]
@e-t-l that doesn't bc the game doesn't recognize touch inputs while the touchpad is held down. Instead I enabled a toggle with L3+R3 for switching between regular dpad and dpad touch so the 2 don't conflict with each other.

**Comment by streetpea** [comment]
@e-t-l here is the updated build: https://github.com/streetpea/chiaki-ng/actions/runs/11865505681/artifacts/2195649923

**Comment by e-t-l** [comment]
Thanks! I assume the change you made was just in the backend, not in the GUI? It would be good to be able to assign what button combination performs the toggle, since L3+R3 is actually an assigned button combo in Ghost of Tsushima already. Or maybe assign it to b6+b7, do any games use that combo?

And regarding my original idea, where the touchpad button would work as a modifier key...

> the game doesn't recognize touch inputs while the touchpad is held down

To clarify, I was suggesting that when the touchpad button is held and a d-pad button is pressed, that overrides the "touchpad down" input and sends the touchpad swipe input instead. (I guess this would be a problem if a game has assigned controls to both touchpad long-press and touchpad swipes, but I don't know of any games that do that.) My suggested feature could also be a checkbox in chiaki-ng's Controllers settings, so if it causes conflicts for users they can simply disable it, thus reverting chiaki-ng's behavior to how it works currently.

**Comment by streetpea** [comment]
@e-t-l your suggestion was one of the things I tried and it doesn’t work in ghost of Tsushima. If a touchpad press happens immediately before a swipe it still doesn’t recognize the swipe. Unless you completely turn off the touchpad press input (which is used in ghost of Tsushima so you don’t want to do that). Also I tested toggling dpad touch with ghost of Tsushima using l3 + r3 and it worked fine for me. I could change it to l3+r3+l1 though as I don’t think any game has that mapped.

**Comment by e-t-l** [comment]
> If a touchpad press happens immediately before a swipe it still doesn’t recognize the swipe

Oh ok, this was what I didn't understand. Thank you for explaining.

>  tested toggling dpad touch with ghost of Tsushima using l3 + r3 and it worked fine for me

L3+R3 triggers Ghost Mode (a late-game ability) in Ghost of Tsushima. You can see a full list of controls/combos for this game here: https://ghostoftsushima.fandom.com/wiki/Controls (and L1 is the Block button, so it's possible that a player might want to trigger Ghost Mode while blocking)

I don't think any game uses b6+b7 since b6 is normally the Share button and doesnt have in-game use, so I do still think that would be the better combo. Or just let users assign a custom button combo to it in chiaki-ng custom controller assignment settings.

Btw, thanks for taking the time to address this so promptly!

**Comment by streetpea** [comment]
I've changed the default to `L1+R1+Dpad Up`. I've also made it configurable in settings->Controllers. Here is a new build: https://github.com/streetpea/chiaki-ng/actions/runs/11882603502/artifacts/2198912956
