### ISSUE TITLE
[BUG]Mouse cursor did not return when hovering off Chiaki, clicking off Chiaki or even after closing Chiaki

### ISSUE THREAD

**Issue by Jayinem** [streetpea/chiaki-ng#490]
I tried everything including Ctrl+Alt+Delete but nothing worked. I had to sign out. Please I beg you give an option for mouse cursor to remain. Just let everyone decide on that if they need it or not. 

And also I've proven everything I said to this point, so please don't doubt this happened. It really just happened using PS4. You don't have a PS4 console. Maybe on PS5 it wouldn't happen.

**Comment by streetpea** [comment]
You are talking about the cursor on your Windows PC?  Which PlayStation console you use has no effect on the PlayStation cursor behavior.

**Comment by streetpea** [comment]
I can certainly add an option to change the in-app cursor color from clear to a solid one.

**Comment by streetpea** [comment]
Also you haven't proven  everything you've said. Many of the things you've said have been wrong. The errors have been correct but your reasoning as to what is going wrong has been incorrect. Which is why when I try to reproduce I can't because it's actually caused by something different than what you're claiming. That is why I am trying to pry for more info not because I don't believe you are running into the error.

**Comment by streetpea** [comment]
You can now disable hiding the cursor during streams by unchecking the hide cursor during stream checkbox in the video section of the settings. https://github.com/streetpea/chiaki-ng/actions/runs/12065799882/artifacts/2248743349

**Comment by Jayinem** [comment]
Thanks
