### ISSUE TITLE
[Feature Request] Native Steam Link Support

### ISSUE THREAD

**Issue by Jademalo** [streetpea/chiaki-ng#52]
I know this is probably (definitely) out of scope, but the original Chiaki project is in maintainance. This seems to be the only project actively working on it, and this build is ultimately about the steam ecosystem.

Is there any possibility of this being compiled as a native Steam Link app?

There aren't many native link apps, the most notable being Kodi and Moonlight. However, the current method to use Chiaki on a steam link is to stream it running on another pc, essentially double streaming the video.
Having a native app would allow the link to be used as an easy stream box like the deck, and honestly would be super useful!

**Comment by jbaiter** [comment]
Chiaki is actually being actively developed last I heard, there's just no issue tracker for it.
I'll look into it, looking at Moonlight's CI build, they're using a pretty ancient version of Ubuntu, that might be an issue, but it's worth a shot.

**Comment by Jademalo** [comment]
Oh that's interesting, the readme on the seemed to imply it was finished - https://git.sr.ht/~thestr4ng3r/chiaki#project-status

I had a quick look from my end and it didn't seem too complex, but it was definitely out of my ability. Valve does have [a proper SDK](https://github.com/ValveSoftware/steamlink-sdk) available, at least.

**Comment by streetpea** [comment]
I don't know if I can add that and keep it under the current license according to [Steam's documentation](https://partner.steamgames.com/doc/sdk/uploading/distributing_opensource) since the initial Chiaki project is GPL3 and hence chiaki4deck is GPL3 and so couldn't be published using the Steam SDK without an exception which would have to be provided by the original Chiaki creator @thestr4ng3r (unless I'm missing something from the above link).

**Comment by Jademalo** [comment]
I believe that license is for actually publishing through the steam store front, I don't think it's relevant in terms of compiling using the steam deck tool chain.

Simply compiling and distributing the binary through here for manual install should be within the license terms, as far as I can tell.

The steamworks SDK is a different thing to the steam deck compilation toolchain

**Comment by streetpea** [comment]
kk, I can look into that down the line then, if it doesn't break the licensing and enables it to have Steam game functionality like Steam Input (as @Jademalo mentioned above) that would be useful ... or if someone else wants to take a stab at it that would work too of course :)

**Comment by cgarst** [comment]
@streetpea I am exploring cross-compiling chiaki-ng to the steam link ARM device, though it's SDK may be too old to be practical.

It looks like an initial challenge is that the SDK supports Qt5, not Qt6. It may be possibly to build Qt6 for distribution and dynamically link to it, though there's licensing questions I need to research there. It looks like chiaki-ng is probably married to Qt6 at this point, though I see some compatibility stuff living in `scripts/` which sort of indicate otherwise. Is chiaki-ng Qt6 or bust at this point?

Another challenge may be that the device's SDK is geared to support OpenGL ES 2.0 as the graphics API. I haven't seen that utilized before and it's unclear if ffmpeg would provide a path to hardware decoding. Has this API come up for other targets in the past?

**Comment by streetpea** [comment]
@cgarst chiaki-ng has completely moved to Vulkan rendering and qt6

**Comment by cgarst** [comment]
That makes sense, not a good fit for chiaki-ng then. I'll see what I can do with forking OG chiaki.

**Comment by streetpea** [comment]
@cgarst based on your comments and the current state of chiaki-ng it sounds like it’s not possible to support Steam Link. Thus, I’m closing this issue.

**Comment by Jademalo** [comment]
Good luck @cgarst , let me know if you're successful!
